version: 2.1
orbs:
  nais: 'navikt/nais-deployment@3.2.0'

jobs:
  bygg-og-push-docker:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          TZ: "Europe/Oslo"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run:
          name: Gradle build
          command: gradle build
      - setup_remote_docker
      - run:
          name: Docker build
          command: docker build -t "navikt/dittnav-event-test-producer:$CIRCLE_SHA1" -t "navikt/dittnav-event-test-producer:latest" .
      - run:
          name: Docker push
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
            docker push "navikt/dittnav-event-test-producer:$CIRCLE_SHA1"
            docker push "navikt/dittnav-event-test-producer:latest"
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

workflows:
  bygg-og-deploy:
    jobs:
      - bygg-og-push-docker:
          context: NAIS deployment
      - til-q6:
          type: approval
          requires:
            - bygg-og-push-docker
      - nais/deploy-gh-app:
          name: q6-deploy
          build-and-push-docker-image: false
          repo: navikt/dittnav-event-test-producer
          image: navikt/dittnav-event-test-producer
          github-app-id: 34043
          nais-template: nais/nais.yaml
          environment: dev-sbs
          team: personbruker
          enable-vars: true
          template-vars: nais/dev/q6.json
          requires:
            - til-q6
      - til-q1:
          type: approval
          requires:
            - q6-deploy
      - nais/deploy-gh-app:
          name: q1-deploy
          build-and-push-docker-image: false
          repo: navikt/dittnav-event-test-producer
          image: navikt/dittnav-event-test-producer
          github-app-id: 34043
          nais-template: nais/nais.yaml
          environment: dev-sbs
          team: personbruker
          enable-vars: true
          template-vars: nais/dev/q1.json
          requires:
            - til-q1
      - til-q0:
          type: approval
          requires:
            - q1-deploy
          filters:
            branches:
              only: master
      - nais/deploy-gh-app:
          name: q0-deploy
          build-and-push-docker-image: false
          repo: navikt/dittnav-event-test-producer
          image: navikt/dittnav-event-test-producer
          github-app-id: 34043
          nais-template: nais/nais.yaml
          environment: dev-sbs
          team: personbruker
          enable-vars: true
          template-vars: nais/dev/q0.json
          requires:
            - til-q0
