apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-test-producer
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/dittnav-event-test-producer/isAlive
    initialDelay: 5
  readiness:
    path: /person/dittnav-event-test-producer/isReady
    initialDelay: 5
  prometheus:
    path: /person/dittnav-event-test-producer/metrics
  replicas:
    min: 1
    max: 1
  webproxy: true
  ingresses: {{ingresses}}
  vault:
    enabled: true
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{kafkaBootstrapServers}}
    - name: KAFKA_SCHEMAREGISTRY_SERVERS
      value: {{kafkaSchemaregistryServers}}
    - name: GROUP_ID
      value: {{groupId}}
    - name: DB_NAME
      value: {{dbName}}
    - name: DB_HOST
      value: {{dbHost}}
    - name: DB_MOUNT_PATH
      value: {{dbMountPath}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
