apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-event-test-producer
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/dittnav-event-test-producer/isAlive
    initialDelay: 5
  readiness:
    path: /person/dittnav-event-test-producer/isReady
    initialDelay: 5
  prometheus:
    path: /person/dittnav-event-test-producer/metrics
  replicas:
    min: 1
    max: 1
  webproxy: true
  ingresses:
{{#each ingresses}}
  - "{{this}}"
{{/each}}
  vault:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
