ALTER TABLE DONE RENAME COLUMN aktorId TO fodselsnummer;
ALTER TABLE DONE RENAME COLUMN dokumentid TO grupperingsId;
ALTER TABLE BESKJED RENAME COLUMN aktorId TO fodselsnummer;
ALTER TABLE BESKJED RENAME COLUMN dokumentid TO grupperingsId;
ALTER TABLE OPPGAVE RENAME COLUMN aktorId TO fodselsnummer;
ALTER TABLE OPPGAVE RENAME COLUMN dokumentid TO grupperingsId;
ALTER TABLE INNBOKS RENAME COLUMN aktorId TO fodselsnummer;
ALTER TABLE INNBOKS RENAME COLUMN dokumentid TO grupperingsId;