name: Kjør ende-til-ende-tester ved pull-request

on:
  push:
    branches:
      - 'gh-actions-test'

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sjekk ut koden for dette repo-et'
        uses: actions/checkout@v2
      - name: 'Sjekk ut dittnav-docker-compose'
        uses: actions/checkout@v2
        with:
          repository: navikt/dittnav-docker-compose
          ref: fjerne-testcontainers
          path: dittnav-docker-compose
          token: ${{ secrets.DOCKER_PKG_TOKEN }}
      - name: 'Docker pull and run'
        uses: actions/checkout@v2
        run: |
          echo "${{ secrets.DOCKER_PKG_TOKEN }}" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          cd dittnav-docker-compose
          docker-compose pull
          docker-compose up -d
          ./gradlew test
          docker-compose down -v

