name: Kjør ende-til-ende-tester ved pull-request

on:
  push:
    branches:
      - 'gh-actions-test'

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sjekk ut koden for dette repo-et'
        uses: actions/checkout@v2
      - name: 'Sjekk ut dittnav-docker-compose'
        uses: actions/checkout@v2
        with:
          repository: navikt/dittnav-docker-compose
          ref: gh-action
          path: dittnav-docker-compose
          token: ${{ secrets.DOCKER_PKG_TOKEN }}
      - name: 'Pull dittnav-docker-compose'
        run: |
          echo "${{ secrets.DOCKER_PKG_TOKEN }}" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          cd dittnav-docker-compose
          docker-compose pull
          cd ..
      - name: 'Docker build and tag latest'
        run: |
          ./gradlew $GRADLE_CMD_BUILD
          docker build --tag $IMAGE_LATEST .
      - name: 'Run end-to-end-tests'
        run: |
          cd dittnav-docker-compose
          ./gradlew test

